[package]
name = "pallet-xcm-benchmarks"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
version = "0.9.27"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
scale-info = { version = "2.1.2", default-features = false, features = ["derive"] }
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate" , branch = "master" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate" , branch = "master" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate" , branch = "master" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate" , branch = "master" }
xcm-executor = {git = "https://github.com/paritytech/polkadot" , branch = "master", default-features = false, features = ["runtime-benchmarks"] }
frame-benchmarking = { default-features = false, git = "https://github.com/paritytech/substrate" , branch = "master" }
xcm = { git = "https://github.com/paritytech/polkadot" , branch = "master", default-features = false, features = ["runtime-benchmarks"] }
log = "0.4.17"

[dev-dependencies]
pallet-balances = { git = "https://github.com/paritytech/substrate" , branch = "master" }
pallet-assets = { git = "https://github.com/paritytech/substrate" , branch = "master" }
sp-core = { git = "https://github.com/paritytech/substrate" , branch = "master" }
sp-io = { git = "https://github.com/paritytech/substrate" , branch = "master" }
sp-tracing = { git = "https://github.com/paritytech/substrate" , branch = "master" }
xcm-builder = { git = "https://github.com/paritytech/polkadot", branch = "master" }
xcm = { git = "https://github.com/paritytech/polkadot" , branch = "master" }
pallet-xcm = { git = "https://github.com/paritytech/polkadot" , branch = "master" }
polkadot-runtime-common = { git = "https://github.com/paritytech/polkadot" , branch = "master" }
polkadot-primitives = { git = "https://github.com/paritytech/polkadot" , branch = "master" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"sp-runtime/std",
	"sp-std/std"
]
